implement QueryAUC metric
catboost/catboost pull request #1598
Opened 2021-03-03 19:55 UTC by fibersel

This Pull Request closes [#1593](https://github.com/catboost/catboost/issues/1593)

2021-03-05 16:10 UTC, ek-ak requested changes

2021-03-09 14:37 UTC, ek-ak commented
@arcadia-devtools Ship it!

2021-03-09 14:59 UTC, arcadia-devtools commented
CLA already signed

2021-03-09 14:59 UTC, arcadia-devtools commented
@ek-ak, internal review request created: [1675602](https://a.yandex-team.ru/review/1675602)

2021-03-11 17:27 UTC, merged