Return models after CV
catboost/catboost pull request #1631
Opened 2021-04-06 08:12 UTC by vklyukin

Closes #1524

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

2021-04-08 04:47 UTC, Evgueni-Petrov-aka-espetrov commented
@arcadia-devtools Ship it!

2021-04-08 04:54 UTC, arcadia-devtools commented
CLA already signed

2021-04-08 04:55 UTC, arcadia-devtools commented
@Evgueni-Petrov-aka-espetrov, internal review request created: [1729111](https://a.yandex-team.ru/review/1729111)

2021-04-08 07:56 UTC, arcadia-devtools commented
Check [1729111](https://a.yandex-team.ru/review/1729111) failed: 5 test(s) broken

2021-04-08 08:07 UTC, Evgueni-Petrov-aka-espetrov requested changes

2021-04-08 08:07 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/ut/medium/test.py
> +        assert model.get_all_params().keys() == single_model.get_all_params().keys()
this assert fails on fresh master as follows -- please fix
```python
catboost/python-package/ut/medium/test.py:2974: in test_cv_return_models
    assert model.get_all_params().keys() == single_model.get_all_params().keys()
E   AssertionError: assert ['bayesian_ma...s_count', ...] == ['bayesian_mat...s_count', ...]
E     Right contains more items, first extra item: 'class_names'
E     Full diff:
E     [u'bayesian_matrix_reg',
E     u'leaf_estimation_backtracking',
E     u'has_time',
E     u'min_data_in_leaf',
E     u'model_shrink_rate',
E     u'classes_count',
E     u'max_leaves',
E     u'counter_calc_method',
E     u'iterations',
E     u'max_ctr_complexity',
E     u'combinations_ctr',
E     u'sparse_features_conflict_fraction',
E     u'boosting_type',
E     u'task_type',
E     u'pool_metainfo_options',
E     u'posterior_sampling',
E     u'sampling_frequency',
E     u'loss_function',
E     u'l2_leaf_reg',
E     u'border_count',
E     u'ctr_leaf_count_limit',
E     u'bootstrap_type',
E     u'auto_class_weights',
E     u'rsm',
E     u'use_best_model',
E     u'leaf_estimation_iterations',
E     u'random_seed',
E     u'eval_metric',
E     u'permutation_count',
E     u'learning_rate',
E     u'nan_mode',
E     u'penalties_coefficient',
E     u'simple_ctr',
E     u'fold_permutation_block',
E     u'one_hot_max_size',
E     u'best_model_min_trees',
E     u'model_shrink_mode',
E     u'score_function',
E     u'store_all_simple_ctr',
E     u'boost_from_average',
E     u'model_size_reg',
E     u'grow_policy',
E     u'ctr_target_border_count',
E     u'random_strength',
E     u'subsample',
E     u'depth',
E     u'feature_border_type',
E     -  u'leaf_estimation_method']
E     ?                           ^
E     +  u'leaf_estimation_method',
E     ?                           ^
E     +  u'class_names']
```

2021-04-16 10:22 UTC, Evgueni-Petrov-aka-espetrov approved these changes

2021-04-16 10:22 UTC, Evgueni-Petrov-aka-espetrov commented
@arcadia-devtools Ship it!

2021-04-16 10:39 UTC, arcadia-devtools commented
@Evgueni-Petrov-aka-espetrov, internal review request updated: [1729111](https://a.yandex-team.ru/review/1729111)

2021-04-16 11:01 UTC, arcadia-devtools commented
@Evgueni-Petrov-aka-espetrov, internal review request updated: [1729111](https://a.yandex-team.ru/review/1729111)

2021-04-16 13:32 UTC, arcadia-devtools commented
Check [1729111](https://a.yandex-team.ru/review/1729111) passed

2021-04-19 16:54 UTC, merged