Make catboost widget works in jupyter lab
catboost/catboost pull request #1636
Opened 2021-04-07 20:02 UTC by Dm17r1y

Before submitting a pull request, please do the following steps:

1. Read [instructions for contributors](https://catboost.ai/docs/concepts/development-and-contributions.html).
2. Run `ya make` in catboost folder to make sure the code builds.
3. Add tests that test your change.
4. Run tests using `ya make -t -A` command.
5. If you haven't already, complete the [CLA](https://yandex.ru/legal/cla/).

2021-04-14 14:51 UTC, LyzhinIvan requested changes

2021-04-14 14:51 UTC, LyzhinIvan commented on catboost/python-package/mk_wheel.py
> +    js_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'widget', 'js')
I've got `No such file error` here - building path from arc_root resolves error.

2021-04-18 15:12 UTC, Dm17r1y commented on catboost/python-package/mk_wheel.py
> +    js_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'widget', 'js')
Fixed: now build path from `arc_root`

2021-04-19 07:38 UTC, LyzhinIvan approved these changes

2021-04-21 07:03 UTC, LyzhinIvan requested changes

2021-04-21 07:03 UTC, LyzhinIvan commented on catboost/python-package/mk_wheel.py
> +    widget_args = [arg for arg in sys.argv[1:] if arg.startswith('-DBUILD_WIDGET=')]
Let's make it simpler by using standard ArgumentParser:
```
widget_args_parser = ArgumentParser()
widget_args_parser.add_argument('--build-widget', choices=['yes', 'no'], default='yes')
widget_args, catboost_args = widget_args_parser.parse_known_args()
should_build_widget = widget_args.build_widget == 'yes'
```

2021-04-22 07:30 UTC, LyzhinIvan approved these changes

2021-04-22 07:31 UTC, LyzhinIvan commented
@arcadia-devtools Ship it!

2021-04-22 07:38 UTC, arcadia-devtools commented
CLA already signed

2021-04-22 07:38 UTC, arcadia-devtools commented
@LyzhinIvan, internal review request created: [1752441](https://a.yandex-team.ru/review/1752441)

2021-04-22 16:17 UTC, LyzhinIvan commented
@arcadia-devtools Ship it!

2021-04-23 11:59 UTC, arcadia-devtools commented
@LyzhinIvan, internal review request updated: [1752441](https://a.yandex-team.ru/review/1752441)

2021-04-23 17:04 UTC, merged

2022-04-22 16:33 UTC, cpoptic commented
This may be related to https://github.com/catboost/catboost/issues/262

When fitting a CatBoost model in Visual Studio Code, with the `plot` parameter set to `True`, there are no plots shown while the model is training.
I have both `ipywidgets==7.7.0` and `catboost==1.0.5` installed and `jupyter nbextension enable --py widgetsnbextension` as per the CatBoost docs [here](https://catboost.ai/en/docs/installation/python-installation-additional-data-visualization-packages)
but still there are no plots being displayed in VS Code while fitting a Catboost model.

Why is the catboost model fitting plot not displayed while running the `.fit()` method in Visual Studio Code?  How to fix this?