Add threshold parameter for binary classification
catboost/catboost pull request #1691
Opened 2021-05-07 02:48 UTC by Keksozavr

Add threshold parameter for binary classification in command line and python package.
Added 2 tests: for command line version and python package.
The parameter is optional.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

2021-05-13 21:02 UTC, kizill requested changes

2021-05-13 21:02 UTC, kizill commented on catboost/python-package/catboost/core.py
> +        binclass_probability_threshold=None
Давай из этих параметров удалим, ок?
Просто на самом деле до тех пор, пока ты модель не обучил, обычно не понятно, какую границу ставить и этот параметр будет вводить в заблуждение пользователей тут.

2021-05-14 11:42 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-14 11:43 UTC, kizill approved these changes

2021-05-14 11:54 UTC, arcadia-devtools commented
CLA already signed

2021-05-14 11:54 UTC, arcadia-devtools commented
@kizill, internal review request created: [1777894](https://a.yandex-team.ru/review/1777894)

2021-05-15 10:51 UTC, merged