Provide object-oriented interface for setting up metric parameters
catboost/catboost pull request #1694
Opened 2021-05-08 23:21 UTC by ks-korovina

Resolves #1595.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

2021-05-13 14:25 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-13 14:38 UTC, arcadia-devtools commented
CLA already signed

2021-05-13 16:15 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-13 16:39 UTC, arcadia-devtools commented
@kizill, internal review request updated: [1776258](https://a.yandex-team.ru/review/1776258)

2021-05-13 20:35 UTC, kizill requested changes
косметические правки, а в целом просто невероятно круто!

2021-05-13 20:35 UTC, kizill commented on catboost/libs/metrics/caching_metric.cpp
> +            , PredictionBorder(predictionBorder) {
нерелеватное изменение, дроп

2021-05-13 20:35 UTC, kizill commented on catboost/libs/metrics/metric.cpp
> +    TVector<TParamSet> paramSets;
А почему тут не как везде? В смысле не `return { TParamSet{...`?

2021-05-13 20:35 UTC, kizill commented on catboost/libs/metrics/metric.cpp
> +        TParamSet{
и тут, давайте для единообразия везде одинаково?

2021-05-13 20:35 UTC, kizill commented on catboost/libs/metrics/metric.cpp
> +    paramSets.emplace_back(
и тут :)

2021-05-13 20:35 UTC, kizill commented on catboost/libs/metrics/metric.cpp
> +	            TParamInfo{"top", false, DefaultTopSize},
что-то не так с выравниваниями

2021-05-13 20:35 UTC, kizill commented on catboost/libs/metrics/metric.cpp
> +	            TParamInfo{"top", false, DefaultTopSize}
выравнивание уехало

2021-05-13 20:35 UTC, kizill commented on catboost/python-package/catboost/core.py
> +            raise CatBoostError("Invalid metrics type={}, must be list(), str() or catboost.metrics.BuiltinMetric.".format(type(metrics)))
... or one of builtin catboost.metrics.* class instances.

2021-05-13 20:35 UTC, kizill commented on catboost/python-package/catboost/core.py
> +            raise CatBoostError("Invalid metric type: must be string() or catboost.metrics.BuiltinMetric.")
... or one of builtin catboost.metrics.* class instances.

2021-05-13 20:46 UTC, kizill approved these changes

2021-05-13 22:07 UTC, ks-korovina commented on catboost/libs/metrics/metric.cpp
> +        TParamSet{
Поправили – теперь везде просто литералы.

2021-05-14 12:49 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-14 12:55 UTC, arcadia-devtools commented
@kizill, internal review request updated: [1776258](https://a.yandex-team.ru/review/1776258)

2021-05-14 18:30 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-14 18:32 UTC, arcadia-devtools commented
@kizill, internal review request updated: [1776258](https://a.yandex-team.ru/review/1776258)

2021-05-14 22:13 UTC, merged