Callback Functionality (issue #1304)
catboost/catboost pull request #1697
Opened 2021-05-11 11:44 UTC by qoter

2021-05-13 07:49 UTC, kizill requested changes

2021-05-13 07:49 UTC, kizill commented on catboost/libs/train_lib/cross_validation.cpp
> +    const auto defaultCustomCallbacks = MakeHolder<ICustomCallbacks>();
По идее, инстанциировать интерфейс не очень хорошо, давай тут просто создавать класс `TCustomCallbacks` без коллбека внутри.

2021-05-13 07:49 UTC, kizill commented on catboost/libs/train_lib/cross_validation.cpp
> +    const auto defaultCustomCallbacks = MakeHolder<ICustomCallbacks>();
Инстанциировать интерфейс не очень хорошо, давай тут просто создавать класс TCustomCallbacks без коллбека внутри.

2021-05-13 07:49 UTC, kizill commented on catboost/libs/features_selection/recursive_features_elimination.cpp
> +        const auto defaultCustomCallbacks = MakeHolder<ICustomCallbacks>();
По идее, инстанциировать интерфейс не очень хорошо, давай тут просто создавать класс TCustomCallbacks без коллбека внутри.

2021-05-13 07:49 UTC, kizill commented on catboost/libs/train_lib/train_model.h
> +    virtual bool IsContinueTraining(const TMetricsAndTimeLeftHistory& /*history*/) {
Давай тут уберем реализацию, чтоб это правда было похоже на интерфейс.

2021-05-13 07:49 UTC, kizill commented on catboost/private/libs/hyperparameter_tuning/hyperparameter_tuning.cpp
> +                const auto defaultCustomCallbacks = MakeHolder<ICustomCallbacks>();
По идее, инстанциировать интерфейс не очень хорошо, давай тут просто создавать класс TCustomCallbacks без коллбека внутри.

2021-05-13 07:49 UTC, kizill commented on catboost/python-package/catboost/_catboost.pyx
> +    info = types.SimpleNamespace()
к сожалению, тут придется добавить костылик для совместимости со вторым питоном (внутри не полностью мигрировали весь код на 3-ий, поэтому пока так)
```
if PY_MAJOR_VERSION >= 3:
    info = types.SimpleNamespace()
else:
    from argparse import Namespace
    info = Namespace()
```

2021-05-13 20:42 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-13 21:12 UTC, arcadia-devtools commented
CLA already signed

2021-05-13 21:12 UTC, arcadia-devtools commented
@kizill, internal review request created: [1776887](https://a.yandex-team.ru/review/1776887)

2021-05-14 12:48 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-14 12:55 UTC, arcadia-devtools commented
@kizill, internal review request updated: [1776887](https://a.yandex-team.ru/review/1776887)

2021-05-16 20:10 UTC, kizill approved these changes

2021-05-16 20:10 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-16 20:37 UTC, arcadia-devtools commented
@kizill, internal review request updated: [1776887](https://a.yandex-team.ru/review/1776887)

2021-05-17 15:57 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-17 16:18 UTC, arcadia-devtools commented
@kizill, internal review request updated: [1776887](https://a.yandex-team.ru/review/1776887)

2021-05-18 02:11 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-18 02:26 UTC, arcadia-devtools commented
@kizill, internal review request updated: [1776887](https://a.yandex-team.ru/review/1776887)

2021-05-18 10:45 UTC, merged