Add GPU evaluation for python package
catboost/catboost pull request #1699
Opened 2021-05-11 20:26 UTC by rakalexandra

Added changes for https://github.com/catboost/catboost/issues/972

2021-05-12 15:07 UTC, kizill requested changes

2021-05-12 15:07 UTC, kizill commented on catboost/private/libs/algo/apply.cpp
>      ILocalExecutor* executor)
Предлагаю использовать тут  значение `EFormulaEvaluatorType FormulaEvaluatorType` из класса `TFullModel`, для чего следует добавить метод-геттер `EFormulaEvaluatorType GetEvaluatorType() const` в этом классе.
Соответственно, предлагаю просто в питоне вызывать `model.SetEvaluatorType()` и добавить параметр `task_type` в метод `predict`

2021-05-13 20:46 UTC, kizill approved these changes

2021-05-13 20:46 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-13 21:12 UTC, arcadia-devtools commented
@rakalexandra, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

2021-05-13 21:12 UTC, arcadia-devtools commented
@kizill, internal review request created: [1776886](https://a.yandex-team.ru/review/1776886)

2021-05-17 13:26 UTC, rakalexandra commented
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

2021-05-18 15:03 UTC, kizill commented
@arcadia-devtools Ship it!

2021-05-18 15:32 UTC, arcadia-devtools commented
CLA already signed

2021-05-18 19:25 UTC, kizill commented
@arcadia-devtools Ship it!

2021-08-30 15:20 UTC, closed without merging