Fbeta score
catboost/catboost pull request #2023
Opened 2022-03-06 11:53 UTC by ELitvinova

Before submitting a pull request, please do the following steps:

1. Read [instructions for contributors](https://catboost.ai/docs/concepts/development-and-contributions.html).
2. Run `ya make` in catboost folder to make sure the code builds.
3. Add tests that test your change.
4. Run tests using `ya make -t -A` command.
5. If you haven't already, complete the [CLA](https://yandex.ru/legal/cla/).

2022-03-11 12:11 UTC, LyzhinIvan requested changes

2022-03-11 12:11 UTC, LyzhinIvan commented on catboost/libs/metrics/caching_metric.cpp
> +                result.emplace_back(MakeHolder<TFCachingMetric>(config.Params, beta_param, config.ApproxDimension));
Здесь должно создаваться K метрик, как в CreateMetricClasswise

2022-03-11 12:12 UTC, LyzhinIvan commented on catboost/libs/metrics/caching_metric.cpp
> +        }
Нужна проверка на то, что beta > 0

2022-03-17 08:43 UTC, LyzhinIvan requested changes

2022-03-17 08:43 UTC, LyzhinIvan commented on catboost/libs/metrics/caching_metric.cpp
> +        TConstArrayRef<TConstArrayRef<double>> approx,
Зачем эти отступы добавились?

2022-03-17 09:42 UTC, LyzhinIvan commented
@arcadia-devtools Ship it!

2022-03-17 09:46 UTC, arcadia-devtools commented
CLA already signed

2022-03-17 09:46 UTC, arcadia-devtools commented
@LyzhinIvan, internal review request created: [2392169](https://a.yandex-team.ru/review/2392169)

2022-03-18 09:18 UTC, LyzhinIvan approved these changes

2022-03-18 09:18 UTC, LyzhinIvan commented
@arcadia-devtools Ship it!

2022-03-18 15:29 UTC, arcadia-devtools commented
@LyzhinIvan, internal review request updated: [2392169](https://a.yandex-team.ru/review/2392169)

2022-03-19 09:05 UTC, merged