Add metrics plotter
catboost/catboost pull request #2036
Opened 2022-03-19 14:07 UTC by evgenabramov

Before submitting a pull request, please do the following steps:

1. Read [instructions for contributors](https://catboost.ai/docs/concepts/development-and-contributions.html).
2. Run `ya make` in catboost folder to make sure the code builds.
3. Add tests that test your change.
4. Run tests using `ya make -t -A` command.
5. If you haven't already, complete the [CLA](https://yandex.ru/legal/cla/).

2022-03-28 19:51 UTC, kizill requested changes

2022-03-28 19:51 UTC, kizill commented on catboost/python-package/catboost/widget/callbacks.py
> +import xgboost as xgb
Please make this import optional to make catboost widget independent of xgboost installation.

2022-03-28 19:51 UTC, kizill commented on catboost/python-package/catboost/widget/metrics_plotter.py
> +logging.getLogger().setLevel(logging.DEBUG)
Not needed, i guess.

2022-03-28 19:51 UTC, kizill commented on catboost/python-package/catboost/widget/metrics_plotter.py
> +class MetricsWidget(DOMWidget):
Maybe use common base class for `MetricsWidget` and `MetricVisualizer` to store repeated defs?

2022-03-28 19:51 UTC, kizill commented on catboost/python-package/catboost/widget/metrics_plotter.py
> +logging.getLogger().setLevel(logging.DEBUG)
Maybe create special logger instance for plotter:
```logger = logging.getLogger(__name__)```

2022-03-31 10:13 UTC, kizill commented
@arcadia-devtools Ship it!

2022-03-31 10:26 UTC, arcadia-devtools commented
@evgenabramov, please agree to the CLA (https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md#provide-contributions)

2022-03-31 11:16 UTC, evgenabramov commented
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

2022-03-31 14:24 UTC, kizill approved these changes

2022-03-31 14:28 UTC, arcadia-devtools commented
CLA already signed

2022-03-31 14:28 UTC, arcadia-devtools commented
@kizill, internal review request updated: [2427817](https://a.yandex-team.ru/review/2427817)

2022-03-31 21:19 UTC, merged