Some structure fixes and improvements
catboost/catboost pull request #2235
Opened 2022-11-24 13:56 UTC by elenaspb2019

Some structure fixes and improvements

Before submitting a pull request, please do the following steps:

1. Read [instructions for contributors](https://catboost.ai/docs/concepts/development-and-contributions.html).
2. Run `ya make` in catboost folder to make sure the code builds.
3. Add tests that test your change.
4. Run tests using `ya make -t -A` command.
5. If you haven't already, complete the [CLA](https://yandex.ru/legal/cla/).

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.

2022-11-25 06:28 UTC, Evgueni-Petrov-aka-espetrov requested changes

2022-11-25 06:28 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/docs/en/features/visualization_jupyter-notebook.md
> +   train_dir = "crossentropy")
please add indentation (4 spaces)

2022-11-25 06:28 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/docs/en/features/visualization_jupyter-notebook.md
> +   ["c", "d", 30, 40, 50, 60]]
please add indentation (4 spaces)

2022-11-25 06:28 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/docs/en/features/visualization_jupyter-notebook.md
> +    ["c", "d", 30, 40, 50, 60]]
please add indentation (4 spaces)

2022-11-25 07:34 UTC, elenaspb2019 commented on catboost/docs/en/features/visualization_jupyter-notebook.md
> +    ["c", "d", 30, 40, 50, 60]]
> please add indentation (4 spaces)

Added

2022-11-25 07:35 UTC, elenaspb2019 commented on catboost/docs/en/features/visualization_jupyter-notebook.md
> +   ["c", "d", 30, 40, 50, 60]]
> please add indentation (4 spaces)

Added

2022-11-25 07:35 UTC, elenaspb2019 commented on catboost/docs/en/features/visualization_jupyter-notebook.md
> +   train_dir = "crossentropy")
> please add indentation (4 spaces)

Added

2022-11-25 10:10 UTC, Evgueni-Petrov-aka-espetrov approved these changes

2022-11-25 10:12 UTC, Evgueni-Petrov-aka-espetrov commented
@arcadia-devtools Ship it!

2022-11-25 11:15 UTC, arcadia-devtools commented
CLA already signed

2022-11-25 13:29 UTC, arcadia-devtools commented
@Evgueni-Petrov-aka-espetrov, internal review request created: [3196291](https://a.yandex-team.ru/review/3196291)

2022-11-28 04:57 UTC, Evgueni-Petrov-aka-espetrov approved these changes

2022-11-28 04:57 UTC, Evgueni-Petrov-aka-espetrov commented
@arcadia-devtools Ship it!

2022-11-28 07:39 UTC, arcadia-devtools commented
@Evgueni-Petrov-aka-espetrov, internal review request updated: [3196291](https://a.yandex-team.ru/review/3196291)

2023-05-04 22:22 UTC, andrey-khropov commented
Auto closing of merged PRs has been broken, so I have to close it manually.

2023-05-04 22:22 UTC, closed without merging