Implement exporting of Multiclass models to C++ and Python
catboost/catboost pull request #2283
Opened 2023-01-30 13:43 UTC by antoninkriz

# Implement exporting of Multiclass models to C++ and Python

Fixes #2281, #1364 and #1798

## TODO
- [ ] PR description
- [ ] Tests
- [ ] ...?

2023-05-17 10:06 UTC, antoninkriz commented
@andrey-khropov could you guys please take a look? Conflicts should be resolved.

2023-05-29 00:17 UTC, andrey-khropov requested changes

2023-05-29 00:17 UTC, andrey-khropov commented on catboost/libs/model/model_export/cpp_exporter.cpp
> +        }
I think it is better to always have this member so it would be more explicit that the model has 0 categorical features.

2023-05-29 00:17 UTC, andrey-khropov commented on catboost/libs/model/model_export/cpp_exporter.cpp
>          }
This should always be present, not depending on `forCatFeatures`.

2023-05-29 00:17 UTC, andrey-khropov commented on catboost/libs/model/model_export/resources/apply_catboost_model.cpp
> +        leafValuesPtr += (1 << currentTreeDepth) * model.Dimension;
No multiplication by model.Dimension needed.

2023-05-29 00:17 UTC, andrey-khropov commented on catboost/libs/model/model_export/resources/apply_catboost_model.cpp
> +        const std::vector<std::string>& catFeatures) {
Indent 4 spaces instead of 8

2023-07-12 15:07 UTC, antoninkriz commented on catboost/libs/model/model_export/cpp_exporter.h
> +                          "due to the absence of hash function in the model");
PR for this change is here: https://github.com/catboost/catboost/pull/2430

2023-07-12 15:49 UTC, antoninkriz commented
@andrey-khropov Thank you for the code review, all notes should be fixed now.

2023-07-14 11:49 UTC, closed without merging