CatBoostModel.java: add `byte[]` interface
catboost/catboost pull request #2537
Opened 2023-11-23 22:59 UTC by catap

Here a trivial changes which can be treated as public domain.

Goal: to avoid wrap `byte[]` into stream which will be copied into `byte[]` to be used inside.

2023-11-25 22:06 UTC, andrey-khropov requested changes
Please add a test to CatBoostModelTest.java. You can check that model returns the same predictions when loaded directly from a file or when read from a file to a byte array and then loaded through your new function.

You can find sample model files and features data to use with these models in other tests in that file.

2023-11-25 22:06 UTC, andrey-khropov commented on catboost/jvm-packages/catboost4j-prediction/src/main/java/ai/catboost/CatBoostModel.java
> +        return loadModel(modelPath, "bin");
`modelPath` -> `serializedModel`

2023-11-25 22:09 UTC, andrey-khropov commented
> Here a trivial changes which can be treated as public domain.

I can ask our lawyers whether we can accept such terms but it would be easier if you just agree to [the CLA](https://yandex.ru/legal/cla/)

2023-11-25 22:47 UTC, catap commented
> > Here a trivial changes which can be treated as public domain.
> 
> I can ask our lawyers whether we can accept such terms but it would be easier if you just agree to [the CLA](https://yandex.ru/legal/cla/)

Or I may close that PR and ask you to re-implement it to make things faster? :)

2023-11-26 00:19 UTC, closed without merging

2023-11-26 00:19 UTC, andrey-khropov commented
> > > Here a trivial changes which can be treated as public domain.
> > 
> > 
> > I can ask our lawyers whether we can accept such terms but it would be easier if you just agree to [the CLA](https://yandex.ru/legal/cla/)
> 
> Or I may close that PR and ask you to re-implement it to make things faster? :)

Ok. https://github.com/catboost/catboost/issues/2539