feat: add RMSPE metric and loss
catboost/catboost pull request #2741
Opened 2024-09-21 21:06 UTC by ivan339339

Based on [catboost/issues/1767](https://github.com/catboost/catboost/issues/1767).

Added:
- RMSPE function as eval_metric and loss function
- boost_from_average support 
- tests for new functionality

New loss is compatible with Newton `leaf_estimation_method`.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2024-12-14 00:19 UTC, andrey-khropov requested changes
ELossFunction::RMSPE has to be added to the list in [ValidateCtrTargetBinarization](https://github.com/catboost/catboost/blob/3da23355716b36bb070f0470de41fe1b08db3fd0/catboost/private/libs/options/catboost_options.cpp#L480)

2025-03-16 18:07 UTC, ivan339339 commented
All fixes done

2025-03-29 16:39 UTC, andrey-khropov requested changes

2025-03-29 16:39 UTC, andrey-khropov commented on catboost/libs/metrics/optimal_const_for_loss.h
> +        Y_ASSERT(target.size() == weights.size());
This is wrong. `weights` can be empty. You should replace this check with 

```c++
Y_ASSERT(weights.empty() || (target.size() == weights.size()));
```

2025-03-29 16:39 UTC, andrey-khropov commented on catboost/libs/metrics/optimal_const_for_loss.h
> +        TVector<float> weightsWithTarget = weights.empty()
Please add a comment similar to the comment here: https://github.com/catboost/catboost/blob/70a9b6a086a7dbf67102e50cbfed02b6a0162712/catboost/libs/metrics/optimal_const_for_loss.h#L111

```
// TODO: replace with dispatch by weights.empty()
```

This code makes an unnecessary extra `weightsWithTarget` vector, it should be optimized. But it is ok for now because it is called only once at the start of the training.

2025-04-03 18:51 UTC, ivan339339 commented on catboost/libs/metrics/optimal_const_for_loss.h
> +        TVector<float> weightsWithTarget = weights.empty()
I replaced it with `float weight = weights.empty() ? 1.0f : weights[idx];` in loop

2025-04-03 18:54 UTC, ivan339339 commented on catboost/libs/metrics/optimal_const_for_loss.h
> +        TVector<float> weightsWithTarget = weights.empty()
Or you meant dispatch like this?

```c++
const auto impl = [=] (auto hasWeight) {...}
return DispatchGenericLambda(impl, !weights.empty());
```

2025-04-03 21:55 UTC, andrey-khropov commented on catboost/libs/metrics/optimal_const_for_loss.h
> +        TVector<float> weightsWithTarget = weights.empty()
> ```c++
> const auto impl = [=] (auto hasWeight) {...}
> return DispatchGenericLambda(impl, !weights.empty());
> ```

Yes. But I don't consider this change to be necessary to merge this PR.

2025-04-05 23:36 UTC, ivan339339 commented on catboost/libs/metrics/optimal_const_for_loss.h
> +        TVector<float> weightsWithTarget = weights.empty()
Added `TODO` comment message

2025-04-14 21:45 UTC, andrey-khropov approved these changes

2025-04-15 12:04 UTC, closed without merging